economy:
  enabled: true
  database:
    type: SQLITE
    file-name: "economy"

warps:
  enabled: true
  name-regex: "^[A-Za-z_]{3,10}$" # в названии только англ буквы и _, от 3 до 10 символов
  database:
    type: SQLITE
    file-name: "warps"

chat:
  enabled: true

frames:
  enabled: true

dropping_blocks:
  enabled: true
  database:
    type: SQLITE
    file-name: "dropping_blocks"

action_blocks:
  enabled: true
  database:
    type: SQLITE
    file-name: "action_blocks"